<a href="https://colab.research.google.com/github/KhosrojerdiA/BERT/blob/main/Question_Answering_System_with_Fine_Tuned_BERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pdfplumber

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.4/56.4 kB 1.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 37.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 26.1 MB/s eta 0:00:00


#Question Answering System with Fine-Tuned BERT


#Tokenize with nltk

In [2]:
pdf_txt = """Life insurance is a legally enforceable contract between two parties both of whom are legally qualified to contract. It is therefore, necessary that the terms and conditions of the agreement must be suitably documented in a manner that would make it clear that both parties to the contract are Ad- idem i.e., of the same mind. Ad-Idem means that both the parties understand the same thing in the same sense or are of the same mind on the same subject. There must be consensus or Ad-Idem between the parties to the contract.
This is possible provided all the terms and conditions, rights and duties - privileges and obligations are properly documented in terms which can be clearly interpreted in a court of law. Between two human beings sometime silence means an acceptance. But as the insurer is a legal personality entitled to contract verbal discussion between parties to the contract is not possible and hence there is a need for documentation.
Insurance is also a contract of utmost good faith and enforced only in the distant future. It is therefore necessary that the declarations made by both the parties should be put in black and white for future reference. Any suppression, willful and material shall make the contract void. The insured, therefore, has a duty to declare all that he knows about himself, his health, his financial status in answering questions contained in the proposal form and other ancillary documents which may be required by the insurer.
Age is an important factor in deciding the quantum of premium against a policy. The document proving the age, i.e. age proof must be reliable and the insured has to undertake as to its truthfulness.
Non-standard age proofs are those which are comparatively less reliable and therefore the insurer accepts them with a pinch of salt. In other words the insurer takes certain precautions before accepting such age proofs as final.
Proof of income is the document may become necessary whenever the sum proposed is very high. Normally a sum proposed which is seven to eight times of the declared income is acceptable for insurance. But proposals do come to the insurer when the known source of income of the proposer is much less compared to the amount of insurance desired. A service holder normally does not face this problem as his sources of income are verifiable.
In case of business people, the assessed income is at times much less compared to what is a desirable income for the amount of insurance desired. In such cases the insurer at times calls for assessed income tax returns, or Chartered Accountant’s certificate etc. Such precautions are necessary to eliminate the possibility of moral hazard.
Policy Contract is the policy document is a detailed document and it is the Evidence of the insurance contract which mentions all the terms and conditions of the insurance. The insured buys not the policy contract, but the right to the sum of money and its future delivery. The insurer on its part promises to pay a sum of money, provided of course the insured keeps its part of promise of paying the installments of premium as scheduled.
The pre-amble to the insurance contract makes the above statement clear and states that this policy is issued subject to the conditions and privileges printed on the back of the policy. The endorsements placed on the policy shall also be part of the policy and it also makes a reference to the proposal form saying that that the statements given in the proposal form are the basis of the contract.
The schedule which is printed on the policy document identifies the office which has issued the policy. It states the name of the policyholder, the date of commencement of the policy, an identification number of the policy called policy number. This number is extremely useful for making any reference to the insurer relating to this policy. This shall avoid needless delay.
Beneficiary’s name is also mentioned along with address.
It is necessary to check that it is correct and any mistake should be immediately pointed out for correction. A mistake in the address may misdirect the premium notices and any other future correspondence. It also states the name of the nominee and the date upto which premium has to be paid. The schedule goes on to mention, the type of policy, on the happening of which, the sum assured is payable and to whom it is payable. It of course also mentions when and how long the premium is to be paid.
The policy document is signed by an official of the insurer and dated and stamped as per the provision of the Stamp Act to make it a completely legally enforceable document.
An assignment of a policy in favour of another person or institution can be effected by an endorsement on the policy. Re-assignment can also be done by a subsequent endorsement on the same policy.As a nomination is automatically cancelled due to an assignment, after re-assignment, it is necessary to make a fresh nomination.
In Duplicate policy a policy document is a valuable document and can be used for mortgage etc. Loss of policy document does not absolve the insurer from the liability of payment of policy proceeds when the claim arises. The claim can be settled on the claimants, furnishing an indemnity bond jointly with one surety.
If a policy is irrevocably lost, a duplicate policy can be issued, after following a certain procedure like the insurer satisfies itself of the circumstances leading to loss and being so satisfied the insurer insists upon an advertisement in a news paper, production of an indemnity bond and payment of policy preparation charges and there after a duplicate policy is issued.
Generally nomination is made at the time of taking a policy. In case it is not done, it is possible to make nomination subsequently by an endorsement on the policy. It is also possible to change a nomination subsequently by an endorsement. After marriage, such change in nomination is normally required.
Life insurance being a legally enforceable contract, needs to be documented with details of the rights and obligations of the parties to the contract. Proposal form duly filled in and signed by the proposer is the first document which forms the basis of the contract.
Every time, the insured pays the premium, he receives a premium receipt. The premium needs to be paid in time, non- payment of premium leads to policy-lapses. Re-instatement of the cover is called revival of the policy.
If the policy is not revived, the policy can become a paid up policy for a reduced sum assured under certain conditions.
The policy document mentions in detail all the rights and obligations of the policyholder. The agent is advised to explain the various provisions of the policy to the policyholder.
The wordings in the policy document are of technical nature and hence the need for explaining. If there are certain endorsements on the policy, that need to be explained too.
It needs to be explained that the policy is a valuable document and needs to be kept in safe custody and in the knowledge of the close relatives.
"""

import nltk
nltk.download('punkt')
tokens = nltk.sent_tokenize(pdf_txt)
for t in tokens:
    print(t, "\n")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


Life insurance is a legally enforceable contract between two parties both of whom are legally qualified to contract. 

It is therefore, necessary that the terms and conditions of the agreement must be suitably documented in a manner that would make it clear that both parties to the contract are Ad- idem i.e., of the same mind. 

Ad-Idem means that both the parties understand the same thing in the same sense or are of the same mind on the same subject. 

There must be consensus or Ad-Idem between the parties to the contract. 

This is possible provided all the terms and conditions, rights and duties - privileges and obligations are properly documented in terms which can be clearly interpreted in a court of law. 

Between two human beings sometime silence means an acceptance. 

But as the insurer is a legal personality entitled to contract verbal discussion between parties to the contract is not possible and hence there is a need for documentation. 

Insurance is also a contract of utmos

#Question

In [3]:
user_question = "When can a duplicate policy be issued?"

#Text Preprocessing

In [4]:
import re
import gensim
from gensim.parsing.preprocessing import remove_stopwords


def clean_sentence(sentence, stopwords=False):
  sentence = sentence.lower().strip()
  sentence = re.sub(r'[^a-z0-9\s]', '', sentence)
  if stopwords:
    sentence = remove_stopwords(sentence)
  return sentence

def get_cleaned_sentences(tokens, stopwords=False):
  cleaned_sentences = []
  for row in tokens:
    cleaned = clean_sentence(row, stopwords)
    cleaned_sentences.append(cleaned)
  return cleaned_sentences

##Call Functions

In [5]:
cleaned_sentences = get_cleaned_sentences(tokens, stopwords=True)
cleaned_sentences_with_stopwords = get_cleaned_sentences(tokens, stopwords=False)
print(cleaned_sentences)
print(cleaned_sentences_with_stopwords)

['life insurance legally enforceable contract parties legally qualified contract', 'necessary terms conditions agreement suitably documented manner clear parties contract ad idem mind', 'adidem means parties understand thing sense mind subject', 'consensus adidem parties contract', 'possible provided terms conditions rights duties privileges obligations properly documented terms clearly interpreted court law', 'human beings silence means acceptance', 'insurer legal personality entitled contract verbal discussion parties contract possible need documentation', 'insurance contract utmost good faith enforced distant future', 'necessary declarations parties black white future reference', 'suppression willful material shall contract void', 'insured duty declare knows health financial status answering questions contained proposal form ancillary documents required insurer', 'age important factor deciding quantum premium policy', 'document proving age', 'age proof reliable insured undertake tru

#Install Transfomers

In [6]:
!pip install transformers

##Import BERTForQuestionAnswering

In [7]:
import torch
from transformers import BertForQuestionAnswering
model = BertForQuestionAnswering.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/443 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-large-uncased-whole-word-masking-finetuned-squad were not used when initializing BertForQuestionAnswering: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


##Import BERTTokenizer

In [8]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

#Example:
Answer and Question

In [9]:
answer_text = """The ability of the machine to infer knowledge from
the user documents can be tested based on its ability to answer
the question asked. Conventional Artificial Neural Network
(ANN) models for knowledge extraction only answer to the
questions which are simple and objective as they don't analyze
the questions and don't try to understand what really the content
of document mean. The proposed question answering system
(QAS) uses deep cases along with ANN to understand the
contents of the documents. We divide the sentences of natural
language into knowledge units and assign deep case to each word
to improve the quality of knowledge extraction."""

question = "How to improve the quality of knowledge extraction?"

##Tokenize answer and question
with tokenizer.encode with max_length = 512

In [10]:
input_ids = tokenizer.encode(question, answer_text, max_length=512, truncation=True)
print('The input has a total of {:} tokens.'.format(len(input_ids)))

The input has a total of 130 tokens.


##Get idx and tokens from Tokenizer

In [11]:
tokens = tokenizer.convert_ids_to_tokens(input_ids)
for token, id in zip(tokens, input_ids):
    if id == tokenizer.sep_token_id:
        print('')
    print('{:<12} {:>6,}'.format(token, id))

    if id == tokenizer.sep_token_id:
        print('')

#retrurn token id

[CLS]           101
how           2,129
to            2,000
improve       5,335
the           1,996
quality       3,737
of            1,997
knowledge     3,716
extraction   14,676
?             1,029

[SEP]           102

the           1,996
ability       3,754
of            1,997
the           1,996
machine       3,698
to            2,000
in            1,999
##fer         7,512
knowledge     3,716
from          2,013
the           1,996
user          5,310
documents     5,491
can           2,064
be            2,022
tested        7,718
based         2,241
on            2,006
its           2,049
ability       3,754
to            2,000
answer        3,437
the           1,996
question      3,160
asked         2,356
.             1,012
conventional  7,511
artificial    7,976
neural       15,756
network       2,897
(             1,006
ann           5,754
)             1,007
models        4,275
for           2,005
knowledge     3,716
extraction   14,676
only          2,069
answer        3,43

In [12]:
sep_index = input_ids.index(tokenizer.sep_token_id)
num_seg_a = sep_index + 1
num_seg_b = len(input_ids) - num_seg_a
#Here We Construct the list of 0s and 1s.
segment_ids = [0]*num_seg_a + [1]*num_seg_b
# There should be a segment_id for every input token.
assert len(segment_ids) == len(input_ids)

There should be a segment_id for every input token.

#Find Result: Answer
Start and End Scores using Model

In [13]:
start_scores, end_scores = model(torch.tensor([input_ids]), return_dict=False ,token_type_ids=torch.tensor([segment_ids]))

##Result: Start and End of Answer from Model
Score the question with the context (text or answer)

In [14]:
answer_start = torch.argmax(start_scores)
answer_end = torch.argmax(end_scores)

answer = ' '.join(tokens[answer_start:answer_end+1])

print('Answer: "' + answer + '"')

Answer: "divide the sentences of natural language into knowledge units and assign deep case to each word"


##Return Result: Answer with Token iDs

In [15]:
answer = tokens[answer_start]
answer = tokens[answer_start]

# Select the remaining answer tokens and join them with whitespace.
for i in range(answer_start + 1, answer_end + 1):
  # If it's a subword token, then recombine it with the previous token.
    if tokens[i][0:2] == '##':
        answer += tokens[i][2:]
        # Otherwise, add a space then the token.
    else:
        answer += ' ' + tokens[i]
print('Answer: "' + answer + '"')

Answer: "divide the sentences of natural language into knowledge units and assign deep case to each word"


#Combine All: answer_question Function

In [16]:
def answer_question(question, answer_text):

    input_ids = tokenizer.encode(question, answer_text, max_length=512, truncation=True)

    print('Query has {:,} tokens.\n'.format(len(input_ids)))

    sep_index = input_ids.index(tokenizer.sep_token_id)

    num_seg_a = sep_index + 1

    num_seg_b = len(input_ids) - num_seg_a

    segment_ids = [0]*num_seg_a + [1]*num_seg_b

    assert len(segment_ids) == len(input_ids)

    start_scores, end_scores = model(torch.tensor([input_ids]), return_dict=False, token_type_ids=torch.tensor([segment_ids]))

    all_tokens = tokenizer.convert_ids_to_tokens(input_ids)

    #print(' '.join(all_tokens[torch.argmax(start_scores) : torch.argmax(end_scores)+1]))
    #print(f'score: {torch.max(start_scores)}')
    score = float(torch.max(start_scores))
    answer_start = torch.argmax(start_scores)
    answer_end = torch.argmax(end_scores)
    tokens = tokenizer.convert_ids_to_tokens(input_ids)
    answer = tokens[answer_start]

    for i in range(answer_start + 1, answer_end + 1):

        if tokens[i][0:2] == ' ':
            answer += tokens[i][2:]

        else:
            answer += ' ' + tokens[i]
    return answer, score
    #print('Answer: "' + answer + '"')

##Apply

In [17]:
answer_question(question, answer_text)

Query has 130 tokens.



('divide the sentences of natural language into knowledge units and assign deep case to each word',
 6.490677833557129)

#Limitation of BERT
BERT is 512 tokens to process. how to improve it?

we can split the sentences according to tokens. split upto 512 tokens after that we need to add some special token like [sep] [cls]

In [18]:
pdf_txt

'Life insurance is a legally enforceable contract between two parties both of whom are legally qualified to contract. It is therefore, necessary that the terms and conditions of the agreement must be suitably documented in a manner that would make it clear that both parties to the contract are Ad- idem i.e., of the same mind. Ad-Idem means that both the parties understand the same thing in the same sense or are of the same mind on the same subject. There must be consensus or Ad-Idem between the parties to the contract.\nThis is possible provided all the terms and conditions, rights and duties - privileges and obligations are properly documented in terms which can be clearly interpreted in a court of law. Between two human beings sometime silence means an acceptance. But as the insurer is a legal personality entitled to contract verbal discussion between parties to the contract is not possible and hence there is a need for documentation.\nInsurance is also a contract of utmost good fait

In [19]:
user_question

'When can a duplicate policy be issued?'

##tokenizer.encode with [sep] and [cls] at the end

In [20]:
tokens = tokenizer.encode_plus(user_question, pdf_txt, add_special_tokens=True, max_length=512, truncation=True, padding="max_length")
tokens

Be aware, overflowing tokens are not returned for the setting you have chosen, i.e. sequence pairs with the 'longest_first' truncation strategy. So the returned list will always be empty even if some tokens have been removed.


{'input_ids': [101, 2043, 2064, 1037, 24473, 3343, 2022, 3843, 1029, 102, 2166, 5427, 2003, 1037, 10142, 16306, 3085, 3206, 2090, 2048, 4243, 2119, 1997, 3183, 2024, 10142, 4591, 2000, 3206, 1012, 2009, 2003, 3568, 1010, 4072, 2008, 1996, 3408, 1998, 3785, 1997, 1996, 3820, 2442, 2022, 4848, 8231, 8832, 1999, 1037, 5450, 2008, 2052, 2191, 2009, 3154, 2008, 2119, 4243, 2000, 1996, 3206, 2024, 4748, 1011, 8909, 6633, 1045, 1012, 1041, 1012, 1010, 1997, 1996, 2168, 2568, 1012, 4748, 1011, 8909, 6633, 2965, 2008, 2119, 1996, 4243, 3305, 1996, 2168, 2518, 1999, 1996, 2168, 3168, 2030, 2024, 1997, 1996, 2168, 2568, 2006, 1996, 2168, 3395, 1012, 2045, 2442, 2022, 10465, 2030, 4748, 1011, 8909, 6633, 2090, 1996, 4243, 2000, 1996, 3206, 1012, 2023, 2003, 2825, 3024, 2035, 1996, 3408, 1998, 3785, 1010, 2916, 1998, 5704, 1011, 14310, 1998, 14422, 2024, 7919, 8832, 1999, 3408, 2029, 2064, 2022, 4415, 10009, 1999, 1037, 2457, 1997, 2375, 1012, 2090, 2048, 2529, 9552, 8811, 4223, 2965, 2019, 9920, 1

##What we added?
It return a dictionary containing three key-value pairs, input_ids , token_type_ids , and attention_mask . We have also added return_tensors='pt' to return PyTorch tensors from the tokenizer (rather than Python lists).

In [21]:
tokens = tokenizer.encode_plus(pdf_txt, add_special_tokens=False, return_tensors='pt')
tokens

Token indices sequence length is longer than the specified maximum sequence length for this model (1395 > 512). Running this sequence through the model will result in indexing errors


{'input_ids': tensor([[2166, 5427, 2003,  ..., 2485, 9064, 1012]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1]])}

In [22]:
input_id_chunks = tokens['input_ids'][0].split(510)
mask_chunks = tokens['attention_mask'][0].split(510)

for tensor in input_id_chunks:
  print(len(tensor))

510
510
375


##Tensor Chunk
Now we have our tokenized tensor; we need to break it into chunks of no more than 510 tokens. We choose 510 rather than 512 to leave two places spare to add our [CLS] and [SEP] tokens.

both our input IDs and attention mask tensors.

We need to add padding to our tensor chunks to ensure they satisfy the 512 tensorlength required by BERT.

In [23]:
chunksize = 512

input_id_chunks = list(tokens['input_ids'][0].split(chunksize - 2))
mask_chunks = list(tokens['attention_mask'][0].split(chunksize - 2))

for i in range(len(input_id_chunks)):
    input_id_chunks[i] = torch.cat([
        torch.tensor([101]), input_id_chunks[i], torch.tensor([102])
    ])
    mask_chunks[i] = torch.cat([
        torch.tensor([1]), mask_chunks[i], torch.tensor([1])
    ])

    pad_len = chunksize - input_id_chunks[i].shape[0]
    if pad_len > 0:
        input_id_chunks[i] = torch.cat([
            input_id_chunks[i], torch.Tensor([0] * pad_len)
        ])
        mask_chunks[i] = torch.cat([
            mask_chunks[i], torch.Tensor([0] * pad_len)
        ])

for chunk in input_id_chunks:
    print(chunk)

tensor([  101,  2166,  5427,  2003,  1037, 10142, 16306,  3085,  3206,  2090,
         2048,  4243,  2119,  1997,  3183,  2024, 10142,  4591,  2000,  3206,
         1012,  2009,  2003,  3568,  1010,  4072,  2008,  1996,  3408,  1998,
         3785,  1997,  1996,  3820,  2442,  2022,  4848,  8231,  8832,  1999,
         1037,  5450,  2008,  2052,  2191,  2009,  3154,  2008,  2119,  4243,
         2000,  1996,  3206,  2024,  4748,  1011,  8909,  6633,  1045,  1012,
         1041,  1012,  1010,  1997,  1996,  2168,  2568,  1012,  4748,  1011,
         8909,  6633,  2965,  2008,  2119,  1996,  4243,  3305,  1996,  2168,
         2518,  1999,  1996,  2168,  3168,  2030,  2024,  1997,  1996,  2168,
         2568,  2006,  1996,  2168,  3395,  1012,  2045,  2442,  2022, 10465,
         2030,  4748,  1011,  8909,  6633,  2090,  1996,  4243,  2000,  1996,
         3206,  1012,  2023,  2003,  2825,  3024,  2035,  1996,  3408,  1998,
         3785,  1010,  2916,  1998,  5704,  1011, 14310,  1998, 

In [24]:
for tensor in range(len(input_id_chunks)):
  ans = answer_question(user_question, ' '.join(tokenizer.convert_ids_to_tokens(input_id_chunks[tensor])))
  print(ans)

Be aware, overflowing tokens are not returned for the setting you have chosen, i.e. sequence pairs with the 'longest_first' truncation strategy. So the returned list will always be empty even if some tokens have been removed.


Query has 512 tokens.



Be aware, overflowing tokens are not returned for the setting you have chosen, i.e. sequence pairs with the 'longest_first' truncation strategy. So the returned list will always be empty even if some tokens have been removed.


('[SEP]', 1.9390349388122559)
Query has 512 tokens.



Be aware, overflowing tokens are not returned for the setting you have chosen, i.e. sequence pairs with the 'longest_first' truncation strategy. So the returned list will always be empty even if some tokens have been removed.


('[CLS] when can a duplicate policy be issued ? [SEP] [CLS] precautions are necessary to eliminate the possibility of moral hazard . policy contract is the policy document is a detailed document and it is the evidence of the insurance contract which mentions all the terms and conditions of the insurance . the ins # # ur ##ed buys not the policy contract , but the right to the sum of money and its future delivery . the ins # # ur ##er on its part promises to pay a sum of money , provided of course the ins # # ur ##ed keeps its part of promise of paying the installment # # s of premium as scheduled . the pre - am # # b ##le to the insurance contract makes the above statement clear and states that this policy is issued subject to the conditions and privileges printed on the back of the policy . the endorsement # # s placed on the policy shall also be part of the policy and it also makes a reference to the proposal form saying that that the statements given in the proposal form are the bas

##expand_split_sentences Function

In [25]:
def expand_split_sentences(pdf_txt):
  import nltk
  nltk.download('punkt')
  new_chunks = nltk.sent_tokenize(pdf_txt)
  length = len(new_chunks)
  #for i in range(length):
    #tmp_token = tokenizer.encode(new_chunks[i])
    #print('The input has a total of {:} tokens.'.format(len(tmp_token)))

  new_df = [];
  for i in range(length):
    paragraph = ""
    for j in range(i, length):
      #tmp_str = paragraph + new_chunks[j]
      tmp_token = tokenizer.encode(paragraph + new_chunks[j])
      length_token = len(tmp_token)
      if length_token < 510:
        #print(length_token)
        paragraph = paragraph + new_chunks[j]
      else:
        #print(length_token)
        break;
    #print(len(tokenizer.encode(paragraph)))
    new_df.append(paragraph)
  return new_df
  #for i in new_df:
    #print(i)

###Example

In [26]:
fdi = """Make in India is an initiative which was launched on September 25, 2014, to facilitate investment, foster innovation, building best in class infrastructure, and making India a hub for manufacturing, design, and innovation. The development of a robust manufacturing sector continues to be a key priority of the Indian Government. It was one of the first 'Vocal for Local' initiatives that exposed India's manufacturing domain to the world. The sector has the potential to not only take economic growth to a higher trajectory but also to provide employment to a large pool of our young labour force.
Make in India initiative has made significant achievements and presently focuses on 27 sectors under Make in India 2.0. Department for Promotion of Industry and Internal Trade is coordinating action plans for manufacturing sectors, while Department of Commerce is coordinating service sectors.
The Government of India is making continuous efforts under Investment Facilitation for implementation of Make in India action plans to identify potential investors. Support is being provided to Indian Missions abroad and State Governments for organising events, summits, road-shows and other promotional activities to attract investment in the country under the Make in India banner. Investment Outreach activities are being carried out for enhancing International co-operation for promoting FDI and improve Ease of Doing Business in the country.
India has registered its highest ever annual FDI Inflow of US
 45.15 billion in 2014-2015. In the last six financial years (2014-20), India has received FDI inflow worth US
 681.87 billion).
Steps taken to improve Ease of Doing Business include simplification and rationalization of existing processes. As a result of the measures taken to improve the country’s investment climate, India jumped to 63rd place in World Bank’s Ease of Doing Business ranking as per World Bank’s Doing Business Report (DBR) 2020. This is driven by reforms in the areas of Starting a Business, Paying Taxes, Trading Across Borders, and Resolving Insolvency.
Recently, Government has taken various steps in addition to ongoing schemes to boost domestic and foreign investments in India. These include the National Infrastructure Pipeline, Reduction in Corporate Tax, easing liquidity problems of NBFCs and Banks, policy measures to boost domestic manufacturing. Government of India has also promoted domestic manufacturing of goods through public procurement orders, Phased Manufacturing Programme (PMP), Schemes for Production Linked Incentives of various Ministries.
Further, with a view to support, facilitate and provide investor friendly ecosystem to investors investing in India, the Union Cabinet on 03rd June, 2020 has approved constitution of an Empowered Group of Secretaries (EGoS), and also Project Development Cells (PDCs) in all concerned Ministries/ Departments to fast-track investments in coordination between the Central Government and State Governments, and thereby grow the pipeline of investible projects in India to increase domestic investments and FDI inflow.
The activities under the Make in India initiative are being undertaken by several Central Government Ministries/ Departments and various State Governments. Further, Ministries formulate action plans, programmes, schemes and policies for the sectors being dealt by them. This Department does not maintain information on such formulations by the line ministries."""


####Question

In [27]:
question_fdi = "What were the various steps taken by the government to boost domestic and foreign investment in India?"

####Result

In [28]:
max_score = 0;
final_answer = ""
new_df = expand_split_sentences(fdi)
for new_context in new_df:
  #new_paragrapgh = new_paragrapgh + answer_question(question, answer_text)
  ans, score = answer_question(question_fdi, new_context)
  if score > max_score:
    max_score = score
    final_answer = ans
print(final_answer)
print(max_score)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Query has 498 tokens.

Query has 457 tokens.

Query has 439 tokens.

Query has 510 tokens.



Be aware, overflowing tokens are not returned for the setting you have chosen, i.e. sequence pairs with the 'longest_first' truncation strategy. So the returned list will always be empty even if some tokens have been removed.


Query has 512 tokens.



Be aware, overflowing tokens are not returned for the setting you have chosen, i.e. sequence pairs with the 'longest_first' truncation strategy. So the returned list will always be empty even if some tokens have been removed.


Query has 512 tokens.

Query has 492 tokens.

Query has 465 tokens.

Query has 427 tokens.

Query has 400 tokens.

Query has 378 tokens.

Query has 350 tokens.

Query has 331 tokens.

Query has 284 tokens.

Query has 257 tokens.

Query has 236 tokens.

Query has 206 tokens.

Query has 174 tokens.

Query has 80 tokens.

Query has 57 tokens.

Query has 36 tokens.

national infrastructure pipeline , reduction in corporate tax , easing liquid ##ity problems of n ##bf ##cs and banks , policy measures to boost domestic manufacturing
6.5698466300964355
